
export const manualDraftGlobals = [
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'ejecutado_y_luego_deprecado', summary: 'Implementacion fisica de ARGOS_ROUTER y espejo hibrido', details: 'Importado desde AG_log_2026-04-09.md', next_step: '', source: 'drive:AG_log_2026-04-09.md' },
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'en_espera', summary: 'Pivot a arquitectura API-first (scaffolding local)', details: 'Importado desde AG_log_2026-04-09.md', next_step: '', source: 'drive:AG_log_2026-04-09.md' },
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'finalizado', summary: 'Analisis del documento Antonio_Explanation', details: 'Importado desde AG_log_2026-04-09.md', next_step: '', source: 'drive:AG_log_2026-04-09.md' },
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'finalizado', summary: 'Correccion de la trazabilidad historica', details: 'Importado desde AG_log_2026-04-09.md', next_step: '', source: 'drive:AG_log_2026-04-09.md' }
];

export const manualDraftShadows = [
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'active', summary: 'Revelacion sobre API-First vs local', details: 'El acceso local a J:/ cambia la necesidad de un backend cloud complejo.', next_step: 'Asignar roles correctos entre planificacion y ejecucion local.', source: 'drive:AG_shadow_log_2026-04-09.md', stream: 'shadow' },
    { timestamp: '2026-04-09', actor: 'Antigravity', module: 'Argos', status: 'active', summary: 'Falsa causalidad narrativa en la lectura de Antonio', details: 'El draft reconoce un sesgo de compresion narrativa y exige separar literalidad, tactica y mito operativo.', next_step: 'Mantener trazabilidad quirurgica entre hechos e inferencias.', source: 'drive:AG_shadow_log_2026-04-09.md', stream: 'glitch' }
];

export const legacyGlitches = [
    { id: 'G-001', timestamp: '2026-04-07 14:12 Atlantic/Canary', actor: 'ChatGPT', module: 'Argos raiz', status: 'mitigado', summary: 'mezcla de niveles documentales', details: 'El protocolo raiz contenia incrustado el protocolo antiguo de SCM8.', next_step: 'Mantener separacion logica y documental entre raiz y modulos.', source: 'google_sheet:ARGOS__root_logs/GLITCH_LOG_GENERAL' },
    { id: 'G-002', timestamp: '2026-04-07 23:40 Atlantic/Canary', actor: 'Codex', module: 'Argos / SCM8', status: 'mitigado', summary: 'confusion de capacidad del conector Drive', details: 'El conector de Drive no sirve como via canonica para escribir Markdown crudo.', next_step: 'Usar filesystem local para .md y conector solo para Docs/Sheets/Slides.', source: 'google_sheet:ARGOS__root_logs/GLITCH_LOG_GENERAL' },
    { id: 'G-003', timestamp: '2026-04-07 23:40 Atlantic/Canary', actor: 'Codex', module: 'Argos / SCM8', status: 'mitigado', summary: 'lectura incorrecta de placeholders .gdoc/.gsheet', details: 'Intentar leer placeholders de Google Drive como texto plano produjo errores de sistema.', next_step: 'Tratar .gdoc/.gsheet como punteros y leerlos con el conector adecuado.', source: 'google_sheet:ARGOS__root_logs/GLITCH_LOG_GENERAL' },
    { id: 'G-004', timestamp: '2026-04-07 23:40 Atlantic/Canary', actor: 'Codex', module: 'Argos / SCM8', status: 'mitigado', summary: 'friccion de codificacion en plantillas Markdown', details: 'Aparecio mojibake y fallaron parches grandes por no coincidir el texto esperado.', next_step: 'Normalizar a UTF-8 al crear archivos nuevos y preferir parches pequenos en legados.', source: 'google_sheet:ARGOS__root_logs/GLITCH_LOG_GENERAL' },
    { id: 'G-005', timestamp: '2026-04-07 23:40 Atlantic/Canary', actor: 'Codex', module: 'Argos', status: 'mitigado', summary: 'respuesta no alineada con intencion operativa', details: 'Se respondio con coordinacion textual cuando el Capitan esperaba ejecucion sobre Drive y backlog.', next_step: 'Si el Capitan habla de backlog/bitacora, inspeccionar antes de solo coordinar.', source: 'google_sheet:ARGOS__root_logs/GLITCH_LOG_GENERAL' },
    { id: 'G-006', timestamp: '2026-04-10 00:45', actor: 'Antigravity', module: 'Argos UI', status: 'active', summary: 'colision inter-IA y falso trigger automatico', details: 'La UI y el backend sugirieron automatismos que no despertaban por si solos a un agente real.', next_step: 'Separar mejor feed visible, adaptador y agente realmente activo.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md' },
    { id: 'G-007', timestamp: '2026-04-10 00:54', actor: 'Codex', module: 'Argos UI', status: 'active', summary: 'work packet mal enrutado por ruteo nominal', details: 'Un paquete para Antigravity/Gemini acabo asignado a Codex por simple deteccion nominal en texto libre.', next_step: 'Endurecer parser de destinatario y no decidir por menciones sueltas.', source: 'runtime:argos.events.jsonl' },
    { id: 'G-008', timestamp: '2026-04-10 03:06', actor: 'Codex', module: 'Argos UI', status: 'mitigado', summary: 'hook de riesgos fuera de scope en app.js', details: 'El bloque del visor y de loadRisks quedo fuera de DOMContentLoaded y podia disparar un ReferenceError al arrancar el frontend.', next_step: 'Anadir smoke-test local o comprobacion sintactica antes de dar por valido un parche UI.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md + local:argos-dashboard/app.js' }
];

export const lateRuntimeGlobals = [
    { timestamp: '2026-04-10 02:14', actor: 'Antigravity', module: 'Argos', status: 'finalizado_en_espera', summary: 'Congelacion operativa y borrador de 6 ejes', details: 'Se pausan ejecuciones y se inyectan seis paquetes de trabajo sobre mascaras, sombra y refactor de interfaces.', next_step: 'Esperar activacion o redistribucion de esos frentes.', source: 'runtime:ARGOS_GLOBAL_LOG.md' },
    { timestamp: '2026-04-10 02:21', actor: 'Antigravity', module: 'Argos UI', status: 'finalizado', summary: 'Revision del parche de Codex y encolamiento de 3 tareas UI', details: 'Se reconoce el paso a /api/logbook y se derivan tres tareas UI sin tocar codigo vivo en ese momento.', next_step: 'Ejecutar el patchset UI cuando la cubierta lo active.', source: 'runtime:ARGOS_GLOBAL_LOG.md' },
    { timestamp: '2026-04-10 02:26', actor: 'Antigravity', module: 'Argos UI', status: 'latente', summary: 'Encolamiento de tarea estructural sobre glitches y refactorizacion del inbox', details: 'Se formula la separacion del glitch log y el rediseño profundo de la pestana Cartas.', next_step: 'Materializarlo en el patchset UI canonicamente asignado.', source: 'runtime:ARGOS_GLOBAL_LOG.md' },
    { timestamp: '2026-04-10 02:44', actor: 'Antigravity', module: 'Argos UI', status: 'finalizado', summary: 'Construccion del Visor de Eventos y Burbujas de Alerta', details: 'Se registra endpoints /api/risks y /api/events y un primer visor transversal de riesgos/eventos.', next_step: 'Verificar que la UI y la historia consolidada alimenten bien ese visor.', source: 'runtime:ARGOS_GLOBAL_LOG.md' }
];

export const lateRuntimeShadows = [
    { timestamp: '2026-04-10 02:14', actor: 'Antigravity', module: 'Argos', status: 'active', summary: 'Calibracion psiquica ante riesgo de dispersion', details: 'Se explicita que el Capitan detecta peligro de diversificacion sin asentar output y pide una Sombra Organizacional.', next_step: 'Traducir la intuicion en taxonomia util de riesgos y prioridades.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md' },
    { timestamp: '2026-04-10 02:21', actor: 'Antigravity', module: 'Argos', status: 'active', summary: 'Convergencia de Codex y Antigravity sobre la fragilidad narrativa', details: 'La intuicion sombreada de un agente fue neutralizada por la solucion estructural del otro via snapshot y backend.', next_step: 'Mantener la inteligencia de enjambre sin duplicar nomenclaturas ni acciones.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md' },
    { timestamp: '2026-04-10 02:26', actor: 'Antigravity', module: 'Argos', status: 'active', summary: 'La escision del glitch log es conceptualmente sana', details: 'No conviene mezclar fallos binarios o de CSS con resto interpretativo profundo en la misma sombra.', next_step: 'Dar al glitch su propio carril en la arquitectura y la UI.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md' },
    { timestamp: '2026-04-10 02:44', actor: 'Antigravity', module: 'Argos UI', status: 'active', summary: 'El Visor de Eventos hace navegable la Sombra', details: 'La intuicion junguiana pasa a interfaz cruzable entre logs, feed y tareas.', next_step: 'Alinear el visor con la historia consolidada y no solo con regex de textos vivos.', source: 'runtime:ARGOS_GLOBAL_SHADOW_LOG.md' }
];
